### ISSUE TITLE
Inaccurate Name

### ISSUE THREAD

**Issue by Quantumplation** [malorisdead/Gambot2#1]
This is at least the 4th or 5th generation of Gambot, including aborted rewrites.

**Comment by SupernaviX** [comment]
The current active version IS gambot 2, gambot 1 was a semifunctional perl script

**Comment by MechanicalMann** [comment]
These are good points.  In fact, internally the project was referred to as "Gambot vNext" for quite some time*.  However, since the active version never made a clear numbering distinction between it and the semifunctional Perl script, and other aborted rewrites never received wide adoption, it was decided that from a branding standpoint the currently active version is broadly considered Gambot v1, with the Bucket fork being effectively v0.  Thus the project was dubbed Gambot 2 in order to maintain this continuity of brand from the public perspective**.
______

\* most of last Tuesday
** IDRGAF but I can change it if people (Rob) seriously object

**Comment by Quantumplation** [comment]
As long as gambot3 is reserved for my non-functional rust port that never got off the ground
